### ISSUE TITLE
Display + instead of new group 

### ISSUE THREAD

**Issue by SheepDomination** [Kruemelkatze/vscode-dashboard#38]
Dashboard 2.0.2 is it possible to only show the + for *new groups* rather then displaying the word `new group` ?

**Comment by Kruemelkatze** [comment]
Add this to the customCSS setting:

```css
#tempGroup { color: transparent; }
```
